// Example Pendragon Data
var dynamic_sheet_attrs = {
  "name" : "Merin",
  "player" : "<a href='http://www.obsidianportal.com/profile/AlisonD'>AlisonD</a>",
  "campaign" : "<a href='http://www.obsidianportal.com/campaign/pendragon1'>pendragon1</a>",
  "age" : "20",
  "son_number" : "2",
  "homeland" : "Pengwern",
  "culture" : "",
  "religion" : "British Christian",
  "lord" : "King Blaen",
  "current_class" : "",
  "current_home" : "",
  "chivalry_bonus" : "",
  "religious_bonus" : "",
  "trait_chaste" : "6",
  "trait_lustful" : "14",
  "trait_energetic" : "18",
  "trait_lazy" : "2",
  "trait_forgiving" : "12",
  "trait_vengeful" : "8",
  "trait_generous" : "18",
  "trait_selfish" : "2",
  "trait_honest" : "11",
  "trait_deceitful" : "9",
  "trait_just" : "14",
  "trait_arbitrary" : "6",
  "trait_merciful" : "12",
  "trait_cruel" : "8",
  "trait_modest" : "5",
  "trait_proud" : "15",
  "trait_pious" : "4", 
  "trait_worldly" : "16", 
  "trait_prudent" : "4",
  "trait_reckless" : "16",
  "trait_temperate" : "7",
  "trait_indulgent" : "13",
  "trait_trusting" : "10", 
  "trait_suspicious" : "10", 
  "trait_valorous" : "16",
  "trait_cowardly" : "4",
  "directed_trait1" : "",
  "directed_trait2" : "",
  "passion_loyalty_lord" : "16",
  "passion_love_family" : "15",
  "passion_hospitality" : "15",
  "passion_honor" : "16",
  "passion1_name" : "Loyalty (friends)",
  "passion1" : "18",
  "passion2_name" : "Love (Rania)",
  "passion2" : "18",
  "passion3_name" : "",
  "passion3" : "",

  "equipment_carried" : "Blessed Armour 12 points",

  "siz" : "15",
  "dex" : "20",
  "str" : "18",
  "con" : "18",
  "app" : "18",
  "distinctive_features" : "Red hair, strong voice, green eyes, thigh scar",
  
  "skill_awareness" : "14",
  "skill_boating" : "1",
  "skill_compose" : "0",
  "skill_courtesy" : "16",
  "skill_dancing" : "11",
  "skill_faerie_lore" : "1",
  "skill_falconry" : "3",
  "skill_first_aid" : "10",
  "skill_flirting" : "11",
  "skill_folklore" : "2",
  "skill_gaming" : "3",
  "skill_heraldry" : "3",
  "skill_hunting" : "6",
  "skill_intrigue" : "22",
  "skill_orate" : "10",
  "skill_recognize" : "11",
  "skill_religion1_name" : "Religion (Christian)",
  "skill_religion1" : "2",
  "skill_romance" : "3",
  "skill_singing" : "4",
  "skill_stewardship" : "2",
  "skill_swimming" : "2",
  "skill_tourney" : "5",

  "glory_this_game" : "",
  "glory" : "15781",

  "combat_battle" : "10",
  "combat_horsemanship" : "19",
  "combat_sword" : "25",
  "combat_lance" : "NA",
  "combat_spear" : "18",
  "combat_dagger" : "5",
  "combat_extra1_name" : "Bow",
  "combat_extra1" : "2",
  "combat_extra2_name" : "Grapple",
  "combat_extra2" : "10"

};
