// Example Pendragon Data
var dynamic_sheet_attrs = {
  "name" : "Rania",
  "player" : "<a href='http://www.obsidianportal.com/profile/AlisonD'>AlisonD</a>",
  "campaign" : "<a href='http://www.obsidianportal.com/campaign/pendragon1'>pendragon1</a>",
  "daughtern_number" : "2",
  "homeland" : "Pengwern",
  "culture" : "",
  "religion" : "British Christian",
  "lord" : "King Blaen",
  "current_class" : "",
  "current_home" : "",
  "gentlewoman_bonus" : "",
  "religious_bonus" : "",
  "trait_chaste" : "6",
  "trait_lustful" : "14",
  "trait_energetic" : "18",
  "trait_lazy" : "2",
  "trait_forgiving" : "12",
  "trait_vengeful" : "8",
  "trait_generous" : "18",
  "trait_selfish" : "2",
  "trait_honest" : "11",
  "trait_deceitful" : "9",
  "trait_just" : "14",
  "trait_arbitrary" : "6",
  "trait_merciful" : "12",
  "trait_cruel" : "8",
  "trait_modest" : "5",
  "trait_proud" : "15",
  "trait_pious" : "4", 
  "trait_worldly" : "16", 
  "trait_prudent" : "4",
  "trait_reckless" : "16",
  "trait_temperate" : "7",
  "trait_indulgent" : "13",
  "trait_trusting" : "10", 
  "trait_suspicious" : "10", 
  "trait_valorous" : "16",
  "trait_cowardly" : "4",
  "directed_trait1" : "",
  "directed_trait2" : "",
  "passion_loyalty_lord" : "16",
  "passion_love_family" : "15",
  "passion_hospitality" : "15",
  "passion_honor" : "16",
  "passion1_name" : "Loyalty (friends)",
  "passion1" : "18",
  "passion2_name" : "Love (Merin)",
  "passion2" : "15",
  "passion3_name" : "",
  "passion3" : "",

  "equipment_carried" : "Clothing",

  "siz" : "13",
  "dex" : "15",
  "str" : "12",
  "con" : "17",
  "app" : "25",
  "distinctive_features" : "Green eyes",
  
  "skill_chirurgery" : "20",
  "skill_courtesy" : "12",
  "skill_dancing" : "15",
  "skill_first_aid" : "15",
  "skill_flirting" : "8",
  "skill_industry" : "15",
  "skill_intrigue" : "10",
  "skill_stewardship" : "20",

  "glory_this_game" : "",
  "glory" : "4000",

  "combat_horsemanship" : "14",
  "combat_dagger" : "12",

};
